dev [WIP]

diff --git a/teleclinotify b/teleclinotify
--- a/teleclinotify
+++ b/teleclinotify
@@ -5,7 +5,21 @@ if [ -z "$1" ]
 then
     message="[From: $(hostname)] $(< /dev/stdin)"
 else
-    message="[From: $(hostname)] $@"
+    # exit code
+    # command | tcn -e $?
+    if [ "$1" = "-e" ] && [ -z "$2" ]
+    then
+        if [ "$2" -eq 0 ]
+        then
+            # success
+            message="[From: $(hostname)]{success} ${@:3}"
+        else
+            # error
+            message="[From: $(hostname)]{ERROR} ${@:3}"
+        fi
+    else
+        message="[From: $(hostname)] $@"
+    fi
 fi
 
 curl -s -X POST \
